name: shop_o
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 5.0.1+1

environment:
  sdk: ">=3.4.1 <4.0.0"

dependencies:

  flutter:
    sdk: flutter



  badges: ^3.1.2

  stream_transform: ^2.1.0
  cached_network_image: ^3.4.1
  chat_bubbles: ^1.6.0
  country_code_picker: ^3.0.0
  custom_pop_up_menu: ^1.2.4
  dartz: ^0.10.1
  dots_indicator: ^3.0.0
  equatable: ^2.0.5
  flutter_bloc: ^8.1.6
  flutter_html: ^3.0.0-alpha.3


  flutter_rating_bar: ^4.0.1
  flutter_svg: ^2.0.10+1
  google_fonts: ^6.2.1
  grouped_list: ^6.0.0
  http: ^1.2.2
  image_picker: ^1.1.2
  intl: ^0.19.0
  pinput: ^5.0.0
  shared_preferences: ^2.3.2
  flutter_slidable: ^3.1.1
  sliding_up_panel: ^2.0.0+1
  sliver_tools: ^0.2.12
  timeago: ^3.7.0
  toggle_switch: ^2.3.0
  webview_flutter: ^4.8.0
  dotted_border: ^2.1.0
  flutter_stripe: ^10.1.1
  google_sign_in: ^6.2.1
  flutter_font_awesome_web_names:
    git:
      url: https://github.com/Mythar/flutter_font_awesome_web_names
      ref: master
  flutter_credit_card: ^4.0.1
  shimmer: ^3.0.0
  flutter_countdown_timer: ^4.1.0
  auto_size_text: ^3.0.0
  lazy_load_scrollview: ^1.3.0
  rename: ^3.0.2
  flutter_facebook_auth: ^7.1.1


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.8
  #  dio: ^5.4.3+1
  dash_chat_2: ^0.0.21
  laravel_echo:
    git:
      url: https://github.com/kakajansh/echo.git
      ref: master
#  pusher_client:
#    git:
#      url: https://github.com/DumbDev168/pusher_client.git
#      ref: master
  #onesignal_flutter: ^5.0.4
  another_stepper: ^1.2.2
  intl_phone_field: ^3.2.0
  social_login_buttons: ^1.0.7
  firebase_core: ^3.6.0
  carousel_slider: ^5.0.0
  google_maps_flutter: ^2.9.0
  location: ^7.0.1
  google_maps_webservice: ^0.0.20-nullsafety.5
  geocoding: ^3.0.0
  flutter_screenutil: ^5.9.3
  connectivity_plus: ^6.1.0
  translator: ^1.0.0
  flutter_widget_from_html: ^0.15.3
  html: ^0.15.4
  #appinio_video_player: ^1.3.0
  #geolocator: ^10.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.4
  flutter_launcher_icons: ^0.14.1

  flutter_lints: ^4.0.0

dependency_overrides:
  http: ^1.2.2

flutter:

  uses-material-design: true

  assets:
    - assets/
    - assets/images/
    - assets/icons/
    - assets/stripe/

flutter_icons:
  android: "launcher_icon"
  ios: true
  remove_alpha_ios: true
  image_path: "assets/launcher_icon.png"
